policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
        jira:
          keys:
          - AC
      body:
        required: true
      spellcheck:
        locale: GB
      maximumOfOneCommit: false
      conventional:
        types:
          - chore
          - docs
          - perf
          - refactor
          - style
          - test
          - ci
          - revert
        descriptionLength: 72