require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.1

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ExtraSpacing:
  Exclude:
    - 'bin/*'

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Max: 80

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300

Metrics/AbcSize:
  Max: 30

Rails:
  Enabled: true

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/services/content_outputs/creator_spec.rb'

RSpec/NestedGroups:
  Max: 4

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'
    - 'lib/tasks/*.rake'

Style/IfUnlessModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': '[]'
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '[]'
    '%W': '[]'
    '%x': ()

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/requests/**/*doc_spec.rb'

RSpec/VariableName:
  Exclude:
    - 'spec/support/shared/requests_client_auth_doc.rb'

Rails/SkipsModelValidations:
  Exclude:
   - 'app/controllers/api/v1/admin/presentations_controller.rb'