{{- if .Values.cloudsql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acme-rocket-api.fullname" . }}-cloudsql
  labels:
    {{- include "acme-rocket-api.labels" . | nindent 4 }}
data:
  account.json: {{ .Values.secrets.cloudsql.serviceAccountKey }}
{{- end }}
