apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-rocket-api.fullname" . }}
  labels:
    {{- include "acme-rocket-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "acme-rocket-api.selectorLabels" . | nindent 4 }}
