default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= [Integer(ENV.fetch("RAILS_MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  idle_timeout: <%= Integer(ENV.fetch('DB_IDLE_CONNECTION_TIMEOUT', 300)) %>

development:
  <<: *default
  database: acme_rocket_api_development

test:
  <<: *default
  database: acme_rocket_api_test

production:
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST') %>
  database: <%= ENV.fetch('DATABASE_NAME') %>
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
