default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: acme_rocket_api_development

test:
  <<: *default
  database: acme_rocket_api_test

production:
  <<: *default
  database: acme_rocket_api_production
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
