### Ingress
ingress:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: knowledge.api.staging-sabio.cloud
    nginx.ingress.kubernetes.io/cors-allow-origin: https://authmiddleware.staging-sabio.cloud
  hosts:
    - host: knowledge.api.staging-sabio.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: acme-rocket-api-tls
      hosts:
        - knowledge.api.staging-sabio.cloud

### Autoscaling
replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: false

### Resources
resources:
  requests:
    cpu: 500m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 512Mi

### Affinity
nodeSelector:
  node_type: primary

### Resources
environment:
  APPLICATION_HOST: "https://knowledge.api.staging-sabio.cloud"
  HOST_URL: "https://knowledge.api.staging-sabio.cloud"
  RAILS_ENV: "production"
  RACK_ENV: "production"
  RAILS_LOG_TO_STDOUT: "true"
