name: CI Pipeline
on:
  push:
    branches-ignore:
      - master
  pull_request:
  pull_request_review_comment:
    types: [created]
  workflow_call:
    secrets:
      CONSOLE_SNYK_API_TOKEN:
        required: true

jobs:
  standards:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: setup-go
        name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true

      - id: conform
        name: Enforce Commit Standards
        shell: bash
        run: |
          go install github.com/siderolabs/conform/cmd/conform@latest >/dev/null 2>&1
          conform enforce
  jira:
    runs-on: ubuntu-latest
    steps:

      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v3

      - name: action-jira-linter
        uses: jira-tools/action-jira-linter@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.MONITORING_ATLASSIAN_API_TOKEN }}
          jira-user: ${{ secrets.MONITORING_ATLASSIAN_USER_EMAIL }}
          jira-base-url: https://sabiogroup.atlassian.net
          pr-threshold: 1000
          validate-issue-status: true
          allowed-issue-statuses: |
            In Development
            Development Testing
          fail-on-error: true
  security:
    needs: [standards, jira]
    runs-on: ubuntu-latest
    steps:

      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v3
  
      - name: Scan Dependencies for Vulnerabilities
        uses: ./.github/actions/snyk-scan-dependencies
        with:
          snyk_token: ${{ secrets.CONSOLE_SNYK_API_TOKEN }}
    

