name: Conventional Commits
on:
  push:
jobs:
  standards:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - id: setup-go
        name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true

      - id: conform
        name: Enforce Commit Standards
        shell: bash
        run: |
          go install github.com/siderolabs/conform/cmd/conform@latest >/dev/null 2>&1
          conform enforce --commit-ref=${{ steps.branch-name.outputs.current_branch }}"
