name: CI Pipeline
on:
  push:
    branches-ignore:
      - master
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
    group:
      ${{ github.repository }}-${{ github.event.number || github.head_ref ||
      github.sha }}-${{ github.workflow }}-${{ github.event_name ==
      'pull_request_review_comment' && 'pr_comment' || 'pr' }}
    cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}
jobs:
  standards:
    runs-on: ubuntu-latest
    steps:
      - name: Commit Standards
        run: echo "Checking Commit Standards"
      
      - name: Code Standards
        run: echo "Checking Lint Standards"

  jira:
    runs-on: ubuntu-latest
    steps:
      - name: Jira
        run: echo "Checking Jira Ticket Status"

  security:
    needs: [standards, jira]
    runs-on: ubuntu-latest
    steps:
      - name: Security
        run: echo "Checking Security"
  
  review:
    needs: [security]
    runs-on: ubuntu-latest
    steps:
      - name: Review
        run: echo "Generating Open AI Review Content"
  
  test:
    needs: [review]
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Running Tests"

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building"
  
  deploy-staging:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Input
        id: manual_input
        uses: actions/github-script@6.4.1
        with:
          script: |
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: 'your-username',
              repo: 'your-repository',
              workflow_id: 'manual-input-workflow.yml',
              ref: context.ref
            });
            console.log('Manual input requested:', response.data);

      - name: Check for Input Response
        run: |
          echo "Waiting for user input..."
          sleep 10  # Wait for a few seconds before checking for response
          response=$(curl -s "https://api.github.com/repos/your-username/your-repository/issues?state=open&creator=your-username&labels=manual-input" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}")
          if echo "$response" | jq -e '.[0]' > /dev/null; then
            echo "User input received!"
            # Perform actions based on the user input
          else
            echo "No user input yet..."
            # Retry or handle the absence of user input
          fi
  
      - name: Building for Staging
        run: echo "Building for Staging"
      
      - name: Deploying to Staging
        run: echo "Deployting to Staging"
  

  
    

