name: CI Pipeline
on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
    group:
      ${{ github.repository }}-${{ github.event.number || github.head_ref ||
      github.sha }}-${{ github.workflow }}-${{ github.event_name ==
      'pull_request_review_comment' && 'pr_comment' || 'pr' }}
    cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}
jobs:
  standards:
    uses: sabio-engineering-product/ci-pipeline/.github/workflows/standards.yml@main
    secrets: inherit


  security:
    needs: [standards]
    uses: sabio-engineering-product/ci-pipeline/.github/workflows/security.yml@main
    secrets: inherit
  
  review:
    if: contains(github.event.pull_request.labels.*.name, 'openai')
    needs: [security]
    uses: sabio-engineering-product/ci-pipeline/.github/workflows/review.yml@main
    secrets: inherit
  
  test:
    needs: [security]
    uses: sabio-engineering-product/ci-pipeline/.github/workflows/tests.yml@main
    with:
      database: true
    secrets: inherit

  build:
    needs: [test]
    uses: sabio-engineering-product/ci-pipeline/.github/workflows/build.yml@main
    secrets: inherit
  
  deploy-staging:
    if: contains(github.event.pull_request.labels.*.name, 'staging')
    needs: [build]
    uses: sabio-engineering-product/ci-pipeline/.github/workflows/deploy-staging.yml@main
    secrets: inherit

  deploy-qa:
    if: contains(github.event.pull_request.labels.*.name, 'quality-assurance')
    needs: [build]
    uses: sabio-engineering-product/ci-pipeline/.github/workflows/deploy-qa.yml@main
    secrets: inherit

  qa-testing:
    if: contains(github.event.pull_request.labels.*.name, 'quality-assurance')
    needs: [deploy-qa]
    uses: sabio-engineering-product/ci-pipeline/.github/workflows/qa-testing.yml@main
  
  

  
    

