name: CI Pipeline
on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
    group:
      ${{ github.repository }}-${{ github.event.number || github.head_ref ||
      github.sha }}-${{ github.workflow }}-${{ github.event_name ==
      'pull_request_review_comment' && 'pr_comment' || 'pr' }}
    cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}
jobs:
  standards:
    runs-on: ubuntu-latest
    steps:
      - name: Commit Standards
        run: echo "Checking Commit Standards"
      
      - name: Code Standards
        run: echo "Checking Lint Standards"

      - name: Jira
        run: echo "Checking Jira Ticket Status - Development"

  security:
    needs: [standards]
    runs-on: ubuntu-latest
    steps:
      - name: Security
        run: echo "Checking Security"
  
  review:
    needs: [security]
    runs-on: ubuntu-latest
    steps:
      - name: Review
        run: echo "Generating Open AI Review Content"
  
  test:
    needs: [review]
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Running Tests"

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building"
  
  deploy-staging:
    if: contains(github.event.pull_request.labels.*.name, 'staging')
    needs: [build]
    runs-on: ubuntu-latest
    environment: staging
    steps:      
      - name: Build Container
        run: echo "Building Container for staging"

      - name: Deploy Container
        run: echo "Deploying Container to staging"

  deploy-qa:
    if: contains(github.event.pull_request.labels.*.name, 'quality-assurance')
    needs: [build]
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Jira
        run: echo "Checking Jira Ticket Status - QA"
      
      - name: Build Container
        run: echo "Build Container for QA"

      - name: Deploy Container
        run: echo "Deploying Container to QA"

  qa:
    if: contains(github.event.pull_request.labels.*.name, 'quality-assurance')
    needs: [deploy-qa]
    runs-on: ubuntu-latest
    environment: qa
    steps:      
      - name: Check QA Test Status on the ticket.
        run: echo "Access Execution Status on Tickets"

  
  

  
    

