name: Deploy To QA
on:
  push:
    branches:
      - qa*

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0